import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('dashboard home review guardrails', () => {
  it('keeps the home route state-aware and guided before management output takes over', () => {
    const pageSource = readFileSync(new URL('./page.tsx', import.meta.url), 'utf8')
    const launchControlSource = readFileSync(
      new URL('../../../components/dashboard/customer-launch-control.tsx', import.meta.url),
      'utf8',
    )
    const stateSource = readFileSync(new URL('../../../lib/guided-self-serve.ts', import.meta.url), 'utf8')

    expect(pageSource).toContain('Eerste managementoverview')
    expect(pageSource).toContain('CustomerLaunchControl')
    expect(pageSource).toContain('Open campagne en dashboard')
    expect(pageSource).toContain('Open uitvoerflow')
    expect(pageSource).toContain('getCampaignCompositionState')
    expect(pageSource).toContain('HOME_STATE_ORDER')
    expect(pageSource).toContain('Deels zichtbaar')
    expect(pageSource).toContain('Indicatief, nog dun')
    expect(pageSource).toContain('Launch klaar')
    expect(pageSource).toContain('Rapport eerst')
    expect(pageSource).toContain('deriveGuidedSelfServeDiscipline')
    expect(pageSource).toContain('primaryGuideInvitesNotSent')
    expect(pageSource).toContain('getPrimaryGuideCampaign')
    expect(pageSource).toContain('getPrimaryFirstNextStepCampaign')
    expect(pageSource).toContain('getFirstNextStepGuidance')
    expect(pageSource).toContain('buildCentralHighlights')
    expect(pageSource).toContain('buildReportCandidates')
    expect(pageSource).toContain('FocusPanel')
    expect(pageSource).toContain('First-next-step')
    expect(pageSource).toContain('DashboardHero')
    expect(pageSource).toContain('Trend in portfolio')
    expect(pageSource).toContain('Waar eerst kijken')
    expect(pageSource).toContain('Klaar voor het overleg')
    expect(pageSource).toContain('Recente rapporten')
    expect(pageSource).toContain('dashboard-overview-preview')
    expect(pageSource).toContain('DashboardTabs tabs={portfolioTabs}')
    expect(pageSource).toContain('defaultTabId={portfolioView}')
    expect(pageSource).toContain('Verdiep daarna via portfolio en campagne')
    expect(pageSource).toContain('Mogelijke vervolgroutes')
    expect(pageSource).toContain('!showFirstNextStep')
    expect(pageSource).toContain('campaign.total_completed >= FIRST_INSIGHT_THRESHOLD')
    expect(pageSource).toContain('ExitScan opvolging, reviewmomenten en dossiers')
    expect(pageSource).toContain('Open de preview-adoptie van het Action Center voor ExitScan')
    expect(pageSource).not.toContain('MTO follow-through en dossiers')

    expect(launchControlSource).toContain('Product')
    expect(launchControlSource).toContain('Verisight doet nu')
    expect(launchControlSource).toContain('Jij doet nu')
    expect(launchControlSource).toContain('Open blokkades')
    expect(launchControlSource).toContain('Uitvoerstatus')
    expect(launchControlSource).toContain('Waar je staat')
    expect(launchControlSource).toContain('Dashboard actief')
    expect(stateSource).toContain('Eerste vervolgstap beschikbaar')
  })

  it('keeps cockpit colors semantically disciplined', () => {
    const source = readFileSync(new URL('./page.tsx', import.meta.url), 'utf8')

    expect(source).toContain('<DashboardChip label="Beheeroverzicht" tone="slate" />')
    expect(source).toContain('<DashboardChip label="Klantdashboard" tone="slate" />')
    expect(source).toContain('<DashboardChip label="Boardroom-ready" tone="emerald" />')
    expect(source).toContain('<DashboardChip label="Preview van rapportlaag" tone="slate" />')
    expect(source).toContain('tone={getHomeStateMeta(group.key).tone}')
    expect(source).toContain("tone: 'emerald' as const")
    expect(source).toContain("label: 'Managementduiding gereed'")
    expect(source).toContain('label={primaryGuideStateMeta?.label ?? primaryExecutionState.currentStateLabel}')
    expect(source).toContain("tone={primaryGuideStateMeta?.tone ?? (primaryExecutionState.dashboardVisible ? 'emerald' : 'amber')}")
    expect(source).toContain('<DashboardChip label={primaryFirstNextStepScanDefinition.productName} tone="slate" />')
    expect(source).toContain('dashboard-report-preview')
  })
})
